version: '3'

services:
  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    
    mysql:
       image: mysql:latest
       container_name: mysql_container
       restart: always
       environment:
         MYSQL_ROOT_PASSWORD: your_root_password
         MYSQL_DATABASE: your_database_name
         MYSQL_USER: your_username
         MYSQL_PASSWORD: your_password
       ports:
         - "3306:3306"
       volumes:
         - db_data:/var/lib/mysql
